name: "Maven"

on:
  pull_request:
  push:
    branches:
      - "graylog-repackaging"

jobs:
  build:
    name: "Build"
    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        java-version:
          - "8"

    steps:
      - uses: "actions/checkout@v3"

      - name: "Set up JDK ${{ matrix.version }}"
        uses: "actions/setup-java@v3"
        with:
          java-version: "${{ matrix.java-version }}"
          distribution: "temurin"
          cache: "maven"

      - name: "Build"
        shell: "bash"
        run: |
          mvn --show-version --batch-mode --fail-fast clean package
